Lec02 Linear Regression

In [1]:
import tensorflow as tf

- Step1. Build a Graph

In [2]:
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
X = tf.placeholder(tf.float32, shape=[None])
Y = tf.placeholder(tf.float32, shape=[None])

In [3]:
hypothesis = X*W + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

- step2. Run the graph

In [4]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [5]:
for step in range(2001):
    costvalue, weight, bvalue, _ = sess.run([cost, W, b, train],
                                           feed_dict ={X:[1,2,3,4,5],Y:[2,3,4,5,6]})
print(step, costvalue, weight, bvalue)

2000 2.02039e-07 [ 1.00029087] [ 0.99895006]


- step3. Clost the Session

In [6]:
sess.close()

Lec03 Linear Regression

In [7]:
import tensorflow as tf

- step1. Build a Graph

In [8]:
W = tf.Variable(tf.random_normal([1]), name='weight')
X = tf.placeholder('float', shape=[None])
Y = tf.placeholder('float', shape=[None])

In [9]:
hypothesis = X*W
cost = tf.reduce_sum(tf.square(hypothesis-Y))

In [10]:
# 변수 tensor에는 =로 assign할 수 없음, 대신 W.assign(descent) 이용
learning_rate = 0.1
gradient = tf.reduce_mean((W*X-Y)*X)
descent = W - learning_rate * gradient
update = W.assign(descent)

- step2. Run the graph

In [11]:
x_data = [1,2,3]
y_data = [2,4,3]
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(2001):
     # sess.run에 train = optimizer.minimize(cost)를 넣듯이 update를 넣어줘야함
    costvalue, weight, _ = sess.run([cost, W, update], feed_dict={X:x_data, Y:y_data})
    if step % 100:
        print(costvalue, weight)

3.45821 [ 1.28674519]
3.28367 [ 1.31959748]
3.23402 [ 1.33711863]
3.2199 [ 1.34646332]
3.21588 [ 1.35144711]
3.21474 [ 1.35410511]
3.21442 [ 1.35552275]
3.21432 [ 1.35627878]
3.2143 [ 1.35668206]
3.21429 [ 1.35689712]
3.21429 [ 1.3570118]
3.21429 [ 1.35707295]
3.21429 [ 1.35710561]
3.21429 [ 1.35712302]
3.21429 [ 1.35713232]
3.21429 [ 1.3571372]
3.21429 [ 1.35713983]
3.21429 [ 1.35714126]
3.21429 [ 1.35714197]
3.21429 [ 1.35714233]
3.21429 [ 1.35714257]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35

3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 

3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 

3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 1.35714269]
3.21429 [ 

- step3. closs session

In [13]:
sess.close()

Lec04 multi-variable linear regression

In [14]:
import tensorflow as tf

- step1. Build a graph

In [15]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [16]:
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [17]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.00001)
train = optimizer.minimize(cost)

- step2. run the graph

In [18]:
x_data = [[73, 80, 75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]]
y_data = [152,185,180,196,142]
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [19]:
type(x_data[0][0])

int

In [20]:
for step in range(2001):
    costvalue, weight, bvalue, _ = sess.run([cost, W, b, train], feed_dict={X:x_data, Y:y_data})
    if step % 100 == 0:
        print(step, costvalue, weight, bvalue)
        
print(costvalue, weight, bvalue)

0 100457.0 [[ 0.26280594]
 [ 0.4988429 ]
 [-0.84219414]] [ 0.75370282]
100 825.63 [[ 0.98672915]
 [ 1.17056525]
 [-0.17441455]] [ 0.76659632]
200 823.351 [[ 1.02480853]
 [ 1.15825796]
 [-0.19995904]] [ 0.7715078]
300 821.124 [[ 1.06236219]
 [ 1.14652491]
 [-0.2255507 ]] [ 0.77640688]
400 818.946 [[ 1.09940243]
 [ 1.13535106]
 [-0.25118688]] [ 0.78129369]
500 816.814 [[ 1.13594186]
 [ 1.12472045]
 [-0.27686441]] [ 0.78616822]
600 814.727 [[ 1.1719929 ]
 [ 1.11461759]
 [-0.30258012]] [ 0.7910307]
700 812.682 [[ 1.20756733]
 [ 1.10502815]
 [-0.32833159]] [ 0.79588115]
800 810.678 [[ 1.24267673]
 [ 1.09593713]
 [-0.35411552]] [ 0.80071974]
900 808.714 [[ 1.2773329 ]
 [ 1.0873313 ]
 [-0.37993029]] [ 0.80554646]
1000 806.785 [[ 1.31154525]
 [ 1.07919753]
 [-0.40577254]] [ 0.8103615]
1100 804.893 [[ 1.34532595]
 [ 1.07152176]
 [-0.43164009]] [ 0.81516498]
1200 803.034 [[ 1.3786844 ]
 [ 1.06429195]
 [-0.45753059]] [ 0.81995696]
1300 801.208 [[ 1.41163158]
 [ 1.05749452]
 [-0.48344141]] [ 0.824

- step3. Prediction

In [21]:
print(sess.run(hypothesis, feed_dict={X:[[100,70,101], [90,100,80]]}))

[[ 168.29859924]
 [ 196.5844574 ]]


- step4. close the sess

In [22]:
sess.close()

Lec05 Logistic Classification

- step1. Build a graph.

In [23]:
X = tf.placeholder(tf.float32, shape=[None,2])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [24]:
hypothesis = tf.div(1., 1. + tf.exp(tf.matmul(X,W)))
## 1. 은 실행됨,, 1일떄는 실행 안됨
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)* tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [25]:
# if hypothesis >0.5, True / False --) cast in tf.float32 then 1 / 0
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y), dtype=tf.float32))

- step2. run a graph

In [26]:
x_data = [[2,1],[3,1],[4,3]]
y_data = [[1],[0],[0]]
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [27]:
for step in range(1000):
    weight, bvalue, _ = sess.run([W,b, train], feed_dict={X:x_data, Y:y_data})
print(weight, bvalue)

[[ 0.65511119]
 [-0.42655259]] [-0.4299666]


In [28]:
# step3. close the sess
sess.close()

Lec06 Softmax Classification.

In [1]:
import tensorflow as tf
import os
import numpy as np
os.chdir("C://Users//MinKyu//Desktop//모두의딥러닝")

- step1. make a graph

In [56]:
X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3
W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

In [57]:
compute = tf.matmul(X,W)+b
#hypothesis = tf.nn.softmax(compute)
hypothesis = tf.div(tf.exp(compute), tf.reduce_sum(tf.exp(compute)))

In [58]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

- step2. run a graph

In [71]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[7,1,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
x_

In [60]:
for step in range(2001):
    weight, bvalue, costvalue, _ = sess.run([W,b,cost,optimizer],
                                            feed_dict= {X:x_data, Y:y_data})
print(weight, bvalue, costvalue)

[[-0.75585312 -0.02052454  0.12789632]
 [ 0.84199172 -1.09557688 -0.08057424]
 [-0.33622506 -0.33508578 -0.28135735]
 [-0.04821188  0.99117082 -0.27506155]] [-1.01747978 -0.97373509  1.93203259] 2.35553


Lec06-2 Fancy Softmax Classification

- step1. make a graph

In [61]:
xy = np.loadtxt('lec06-2.txt', delimiter=',', dtype=np.float32)

In [62]:
nb_classes = 7
X = tf.placeholder(tf.float32, [None,16])
Y = tf.placeholder(tf.int32, [None,1]) # 0~6
Y_one_hot = tf.one_hot(Y, nb_classes) # one_hot의 shape = (None,1,7)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes]) # shape = (None, 7)
W = tf.Variable(tf.random_normal([16, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

In [63]:
compute = tf.matmul(X,W)+b
hypothesis = tf.nn.softmax(compute)
cost = tf.reduce_mean(-tf.reduce_sum(Y_one_hot*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
# tf.cast = casts a tensor to a new type
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

- step2. run a graph

In [74]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [78]:
type(x_data[0][0])
type(y_data[0][0])

numpy.float32

In [67]:
for step in range(2001):
    costvalue, weight, bvalue, _ = sess.run([cost, W, b, optimizer],
                                           feed_dict={X: x_data, Y:y_data})
print(costvalue, weight, bvalue)

0.421893 [[-0.01339065 -1.06268668  0.12599498  0.81963027  0.23437886  0.75443125
   1.01244712]
 [-0.96918571  1.56861854 -1.12079096 -0.55996615  0.37604329  1.11136699
   0.78118342]
 [-1.46843326  1.51470244 -0.40498489  1.08820915  0.02841981 -0.52440125
   0.48511273]
 [ 1.66202283  0.21265434 -0.49519944 -0.71835315  0.3763316   0.03348056
  -0.72002786]
 [-0.22797284  0.95440382 -0.15097398  1.85186672 -0.79587519  0.04724719
  -1.76384199]
 [ 0.91688389 -0.1094542   2.011935    0.44191754 -0.05686411  0.86181378
   2.26125526]
 [-0.24667281  0.329864    0.80039382  1.01362073 -0.35145438  0.01390979
   0.49920949]
 [ 1.69439805 -0.51046538 -0.6123578  -1.02765393  1.74761546  0.43686965
  -0.4832935 ]
 [ 0.4859165   1.08964837 -0.09934907 -0.39379933 -0.52900386 -1.26155734
  -1.29338217]
 [ 1.01339936  0.11004823  2.29580307 -0.93528986 -0.26885995  1.03325689
   0.68503106]
 [ 0.42823151  1.4786185   0.04124604 -1.01798213  1.53271782 -0.63243055
   1.44459248]
 [-1.0084219

- step3. predict the value

In [68]:
pred, acu = sess.run([prediction,accuracy], feed_dict={X:x_data, Y:y_data})

In [69]:
print(acu)

0.881188


In [70]:
sess.close()

- Lec07 training/test dataset

In [2]:
X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([4,3]))
b = tf.Variable(tf.random_normal([3]))

In [3]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

- arg_max의 dimension은 one_hot_encoding을 적용할 차원을 알려주는 매개변수이다.
- 0은 열, 1은 행, 2는 면(행열)을 의미함
- a1 = np.array([1,2,3]) #  크기 (3)인 1차원배열
- a2 = np.array([ [1,2,3] ]) #  1x3
- a3 = np.array( [ [1], [2], [3] ]) #  3x1

In [4]:
# hypothesis가 결과물이 [[a],[b],[c]] 이런식으로 나와 axis에 1 대입
prediction = tf.argmax(hypothesis, axis = 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [5]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0]]
x_test = [[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_test = [[0,1,0],[0,0,1],[0,0,1]]

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# range(201) : 0~200을 포함하는 range 객체 생성
for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                    feed_dict={X:x_data, Y:y_data})
print(step, cost_val, W_val)
print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test,Y:y_test}))

200 0.173331 [[-0.99160486 -0.95640808  0.55562723]
 [-0.15559673 -0.81849986 -0.48119408]
 [ 0.03673925 -0.06912151 -1.54703486]
 [-2.17426848  0.21271192 -0.58684093]]
Prediction: [1 1 1]
Accuracy: 0.333333


- Big learning rate // small learning rate
- non-normalizerd 돼있으면 회귀분석의 경우라도 tensorflow에서는
- gradient descent를 이용해서 적합시키기에 발산할 수도있음
- --) Have to normalize datas.

In [1]:
import tensorflow as tf
# one_hot = True : y값을 one_hot_encoding으로 읽음
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


- step1. make a graph

In [2]:
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])
W = tf.Variable(tf.random_normal([784, 10]))
b = tf.Variable(tf.random_normal([10]))

In [3]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [4]:
is_correct = tf.equal(tf.argmax(hypothesis,1), tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [5]:
training_epochs = 15
batch_size = 100

- step2. run a graph

In [6]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], feed_dict={
                            X: batch_xs, Y: batch_ys})
            avg_cost += c / total_batch

        print('Epoch:', '%04d' % (epoch + 1),
              'cost =', '{:.9f}'.format(avg_cost), c)

Epoch: 0001 cost = 2.906195059 0.712173
Epoch: 0002 cost = 1.105622046 1.12848
Epoch: 0003 cost = 0.884015113 0.726286
Epoch: 0004 cost = 0.774217153 0.842699
Epoch: 0005 cost = 0.705546678 0.780897
Epoch: 0006 cost = 0.656266803 0.543357
Epoch: 0007 cost = 0.618841848 0.586499
Epoch: 0008 cost = 0.588645688 1.07342
Epoch: 0009 cost = 0.563591176 0.30411
Epoch: 0010 cost = 0.543051543 0.780991
Epoch: 0011 cost = 0.524470025 0.585001
Epoch: 0012 cost = 0.509155001 0.765588
Epoch: 0013 cost = 0.495251439 0.864613
Epoch: 0014 cost = 0.482929666 0.313063
Epoch: 0015 cost = 0.471051418 0.884082


In [11]:
c

0.58660144

- step3. close the sess

In [ ]:
sess.close()

- Lec08 Tensor Manipulation.

In [1]:
import tensorflow as tf
import numpy as np
import pprint as pp

In [2]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


check dimension

In [15]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
with tf.Session():
    print(tf.shape(t).eval())

[1 2 3 4]


Broadcasting : Operations between the same shapes

In [20]:
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant(3.)
with tf.Session():
    print((matrix1+matrix2).eval())

[[ 6.  6.]]


In [21]:
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([3.,4.])
with tf.Session():
    print((matrix1+matrix2).eval())

[[ 4.  6.]]


Reduce_mean or reduce_sum or argmax : floating point를 사용해야함
- 0 : 행방향
- 1 : 열방향

In [25]:
x = [[1.,2.],[3.,4.]]
with tf.Session():
    print(tf.reduce_mean(x).eval())
    print(tf.reduce_mean(x, axis=0).eval())
    print(tf.reduce_mean(x, axis=1).eval())
    print(tf.reduce_mean(x, axis=-1).eval())
    print(tf.argmax(x, axis=0).eval())

2.5
[ 2.  3.]
[ 1.5  3.5]
[ 1.5  3.5]
[1 1]


Reshape - '-1'의 의미
- (2,2,3) 이므로 [-1,3]이면 [4,3]이 됨

In [27]:
with tf.Session():
    print(tf.reshape(t, shape = [-1,3]).eval())
    print(tf.reshape(t, shape = [-1,1,3]).eval())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


Reshape - 'squeeze', 'expand'

In [28]:
with tf.Session():
    print(tf.squeeze([[0],[1],[2]]).eval())
    print(tf.expand_dims([0,1,2],1).eval())

[0 1 2]
[[0]
 [1]
 [2]]


One hot

In [29]:
with tf.Session():
    print(tf.one_hot([[0],[1],[2],[0]], depth=3).eval())
    t= tf.one_hot([[0],[1],[2],[0]], depth=3)
    print(tf.reshape(t,shape=[-1,3]).eval())

[[[ 1.  0.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  0.  1.]]

 [[ 1.  0.  0.]]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]


Casting
- 변수 형태를 바꿔줌

In [30]:
with tf.Session():
    print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval())
    print(tf.cast([True, False, 1==1, 0==1], tf.int32).eval())

[1 2 3 4]
[1 0 1 0]


Stack - data를 쌓음

In [31]:
x=[1,4]
y=[2,5]
z=[3,6]

with tf.Session():
    print(tf.stack([x,y,z]).eval())
    print(tf.stack([x,y,z], axis=1).eval())

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


Ones and Zeros_like

In [32]:
x = [[0,1,2], [2,1,0]]
with tf.Session():
    print(tf.ones_like(x).eval())
    print(tf.zeros_like(x).eval())

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


Zip

In [33]:
for x, y in zip([1,2,3], [4,5,6]):
    print(x,y)

1 4
2 5
3 6


- Lec09-1. Neural Net for XOR
- Lec09-2. Tensorboard
- decide which tensors you want to log
- Merge all summaries
- Create writer and add graph
- Run summary merge and add_summary
- Launch TensorBoard

In [1]:
import tensorflow as tf
import numpy as np
import os

In [2]:
# np.array로 지정할 때, np.float32 꼭 써줘야함!!
x_data = np.array([[0.,0.],
                   [0.,1.],
                   [1.,0.],
                   [1.,1.]], dtype=np.float32) # 4 x 2
y_data = np.array([[0.],
                   [1.],
                   [1.],
                   [0.]], dtype = np.float32) # 4 x 1

X = tf.placeholder(dtype= tf.float32, shape = [None,2])
# Y의 shape을 [None]으로 했더니 오류남....
Y = tf.placeholder(dtype=tf.float32, shape = [None,1])

In [3]:
# Tensor들을 Layer로 나눔.
# TensorBoard를 이용해 시각화하기 위한 Tensor 추가
with tf.Graph().as_default():
    with tf.name_scope("layer1") as scope:
        w1 = tf.Variable(tf.random_normal([2,6]), name='weight1', dtype=tf.float32)
        b1 = tf.Variable(tf.random_normal([6]), name='bias1', dtype=tf.float32)
        #layer1 = tf.sigmoid(tf.matmul(X,w1)+b1)
        layer1 = tf.matmul(X,w1)+b1
        
        # 1. decide which tensors you want to log
        #w1_hist = tf.summary.histogram("weights1", w1)
        #b1_hist = tf.summary.histogram("biases1", b1)
        #layer1_hist = tf.summary.histogram("layer1", layer1)
    

    with tf.name_scope("layer2") as scope:
        w2 = tf.Variable(tf.random_normal([6,1]), name = 'weight2', dtype=tf.float32)
        b2 = tf.Variable(tf.random_normal([1]), name = 'bias2', dtype=tf.float32)
        hypothesis = tf.sigmoid(tf.matmul(layer1,w2)+b2)
        
        w2_hist = tf.summary.histogram("weights2", w2)
        b2_hist = tf.summary.histogram("biases2", b2)
        hypothesis_hist = tf.summary.histogram("hypothesis", hypothesis)
    


    with tf.name_scope("cost") as scope:
        cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
        cost_summ = tf.summary.scalar("cost",cost)
    
    with tf.name_scope("train") as scope:
        train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(cost)
    
    with tf.name_scope("prediction") as scope:
        predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
        accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
        accuracy_summ = tf.summary.scalar("accuracy", accuracy)  

ValueError: Tensor("layer1/weight1:0", shape=(2, 6), dtype=float32_ref) must be from the same graph as Tensor("Placeholder:0", shape=(?, 2), dtype=float32).

In [4]:
sess = tf.Session()
route = os.getcwd()
# 2. Merge all summaries
summary = tf.summary.merge_all()

# 3. Create writer and add graph
writer = tf.summary.FileWriter("./Tensorboard", sess.graph)
#writer.add_graph(sess.graph)  # Show the graph

sess.run(tf.global_variables_initializer())



for step in range(10001):
    # 4. Run summary merge and add_summary
    s, _ = sess.run([summary, train], feed_dict={X: x_data, Y: y_data})
    writer.add_summary(s, global_step=step)

    if step % 1000 == 0:
        print(step, sess.run(cost, 
                             feed_dict={X: x_data, Y: y_data}))

# Accuracy report
h, c, a = sess.run([hypothesis, predicted, accuracy],
                    feed_dict={X: x_data, Y: y_data})
print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

NameError: name 'train' is not defined

- lec10. mnist_nn, xavier initialization, Dropout

In [4]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot =True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


- step1. make a graph

In [5]:
# input layer
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])
keep_prob = tf.placeholder(tf.float32)

In [6]:
# define FC Layer function
def nn_layer(name, input_data, output_size):
    w = tf.get_variable(name = name + "_w", 
                        shape = [input_data.get_shape().as_list()[1], output_size],
                        # tensor의 모양 get_shape()
                        initializer = tf.contrib.layers.xavier_initializer())
    b = tf.get_variable(name = name + "_b",
                       shape = [output_size],
                       initializer = tf.contrib.layers.xavier_initializer())
    return tf.matmul(input_data, w) + b

# FC Layer
with tf.name_scope("L2"): # [?, 784] --) [?, 14*14]
    L2 = tf.nn.relu(nn_layer("L2", X, 14*14 ))
    L2 = tf.nn.dropout(L2, keep_prob = keep_prob)

with tf.name_scope("L3"): # [?, 14*14] --) [?, 14*14]
    L3 = tf.nn.relu(nn_layer("L3", L2, 14*14))
    L3 = tf.nn.dropout(L3, keep_prob = keep_prob)

with tf.name_scope("L4"): # [?, 14*14] --) [?, 10]
    hypothesis = nn_layer("L4", L3, 10) 

In [7]:
# Loss Layer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy Layer
is_correct = tf.equal(tf.argmax(hypothesis,1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

- step2. Run a graph

In [8]:
training_epochs = 15
batch_size = 100

In [9]:
with tf.Session() as sess:
    # Initialize Tensorflow Variables
    sess.run(tf.global_variables_initializer())
    
    # Training Cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size) # epoch당 batch수
        
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], 
                            feed_dict = { X : batch_xs, Y : batch_ys, keep_prob : 0.7})
            avg_cost += c/total_batch
            
        print('Epoch:', '%04d' % (epoch+1),
             'cost =', '{:.9f}'.format(avg_cost))
    print('Accuracy:', sess.run(accuracy,
                                feed_dict={X : mnist.test.images, Y : mnist.test.labels, keep_prob : 1}))

Epoch: 0001 cost = 0.388544917
Epoch: 0002 cost = 0.300527055
Epoch: 0003 cost = 0.273248309
Epoch: 0004 cost = 0.255698043
Epoch: 0005 cost = 0.254622058


KeyboardInterrupt: 

- Lec 11. MNIST with CNN

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot= True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


- step1. make the graph

In [3]:
# hyper parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

In [4]:
# Input Layer
X = tf.placeholder(tf.float32, [None, 784])
X_img = tf.reshape(X, [-1,28,28,1])
Y = tf.placeholder(tf.float32, [None, 10])
keep_prob = tf.placeholder(tf.float32)

In [5]:
# Conv Layer1 : input : [?, 28, 28 ,1] 
W1 = tf.Variable(tf.random_normal([3,3,1,32], stddev=0.01))
L1 = tf.nn.conv2d(X_img, W1, strides=[1,1,1,1], padding="SAME") # [28,28,32]
L1 = tf.nn.relu(L1)

# Max-pool Layer1
L1 = tf.nn.max_pool(L1, ksize=[1,2,2,1], strides=[1,2,2,1], padding="SAME") # [14,14,32]
L1 = tf.nn.dropout(L1, keep_prob=keep_prob)

# Conv Layer2 : input : [?, 14, 14, 32]
W2 = tf.Variable(tf.random_normal([3, 3, 32, 64], stddev=0.01)) 
L2 = tf.nn.conv2d(L1, W2, strides=[1, 1, 1, 1], padding='SAME') # [14, 14, 64]
L2 = tf.nn.relu(L2)

# Max-Pool Layer2
L2 = tf.nn.max_pool(L2, ksize=[1, 2, 2, 1],
                    strides=[1, 2, 2, 1], padding='SAME') # [7, 7, 64]
L2 = tf.nn.dropout(L2, keep_prob=keep_prob)

# Conv Layer3 : [?, 7, 7, 64]
W3 = tf.Variable(tf.random_normal([3, 3, 64, 128], stddev=0.01))
L3 = tf.nn.conv2d(L2, W3, strides=[1, 1, 1, 1], padding='SAME') # [7, 7, 128]
L3 = tf.nn.relu(L3)

# Max-Pool Layer3
L3 = tf.nn.max_pool(L3, ksize=[1, 2, 2, 1], strides=[
                    1, 2, 2, 1], padding='SAME')
L3 = tf.nn.dropout(L3, keep_prob=keep_prob) # [4, 4, 128]
L3 = tf.reshape(L3, [-1, 128 * 4 * 4])

In [6]:
# FC Layer1 : [?, 128*4*4] --) [?, 625]
W4 = tf.get_variable("W4", shape = [128 * 4 * 4, 625],
                    initializer = tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([625]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4 )
L4 = tf.nn.dropout(L4, keep_prob = keep_prob)

# FC Layer2 : [?, 625] --) [?, 10]
W5 = tf.get_variable("W5", shape=[625, 10],
                     initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L4, W5) + b5

In [7]:
# Loss Layer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(cost)

# Accuracy Layer
correct_prediction = tf.equal(tf.argmax(hypothesis,1), tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

- step2. Run a graph

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print('Learning started. It takes sometime.')
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size) # epoch당 batch수
        
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            # batch별로 optimize 시킴
            c, _ = sess.run([cost, optimizer],
                           feed_dict = {X : batch_xs, Y : batch_ys, keep_prob : 0.7})
            avg_cost += c / total_batch
            
        print('Epoch:', '%04d' % (epoch+1), 'cost=', '{:.9f}'.format(avg_cost))
        
    print('Learning Finished')
    print('Accuracy:', sess.run(accuracy, feed_dict={X: mnist.test.images, Y:mnist.test.labels}))

Learning started. It takes sometime.


KeyboardInterrupt: 